name: Deploy to S3

on:
  push:
    branches:
      - Develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: sa-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./web-site-teste

      - name: Build Angular app
        run: npm run build:prod --prefix ./web-site-teste
      
      - name: Deploy to S3
        if: success()
        run: aws s3 sync ./dist/web-site-teste s3://www.pock-angular.vs